# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-17 19:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.CharField(max_length=2)),
                ('timestamp', models.CharField(max_length=20)),
                ('lifestyle', models.CharField(max_length=10)),
                ('event', models.CharField(max_length=10)),
                ('duration', models.CharField(max_length=20)),
                ('start_time', models.CharField(max_length=20)),
                ('area_title', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.CharField(max_length=2)),
                ('email', models.CharField(max_length=50)),
                ('sex', models.CharField(max_length=10)),
                ('fbid', models.CharField(max_length=100)),
            ],
        ),
    ]
