# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-15 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=7)),
                ('duration', models.DurationField()),
                ('start_time', models.DateTimeField()),
                ('area', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.PositiveSmallIntegerField()),
                ('email', models.EmailField(max_length=50)),
                ('sex', models.CharField(max_length=2)),
                ('fbid', models.URLField(max_length=100)),
            ],
        ),
    ]
